### ISSUE TITLE
Allow to choose between Jenkins Deployment and Deployment Config in CR

### ISSUE THREAD

**Issue by waveywaves** [redhat-developer/openshift-jenkins-operator#56]
This allows the user to choose between Jenkins Deployment or DeploymentConfig as a controller for their Pod. Users for Openshift Jenkins would at times prefer to use the DeploymentConfig, but everyday Kubernetes users would prefer to use DeploymentConfig as they would be using it in their production environments and we would like to keep it that way.

- Jenkins Deployment as the default.
- `useDeploymentConfig` as part of `.spec` (`.spec.useDeploymentConfig`). When `true`, DeploymentConfig is used.
- Imagestream support for Deployment by passing `imagestreamName/image` to `.spec.Image`

**Comment by akram** [comment]
Perfect, that's what we need
